name: Publish

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore CueCompanion.slnx

    - name: Publish project for windows
      run: dotnet publish CueCompanion/CueCompanion.csproj -c Release -o publish-win --self-contained true -r win-x64

    - name: Publish project for linux
      run: dotnet publish CueCompanion/CueCompanion.csproj -c Release -o publish-linux --self-contained true -r linux-x64

    - name: Upload windows build
      uses: actions/upload-artifact@v4
      with:
        name: CueCompanion-Build-win64
        path: publish-win

    - name: Upload linux build
      uses: actions/upload-artifact@v4
      with:
        name: CueCompanion-Build-linux64
        path: publish-linux